### ISSUE TITLE
About per layer info

### ISSUE THREAD

**Issue by touristourist** [mdenna-synaptics/codalab2022#4]
Hi Maurizio, about the JSON file, I have some questions. 
First, does the 'by_layer' field show the inference time per layer? But when I add all the layers' time, the result exceeds the model's 'inference_us' by a large margin.  What's more, there are some layers show 0 μs in the file, I check out my tflite and make sure these layers don't exist in my model.
Second, how to display the correct type of layer? For instance, I created a  Conv2D layer, usually, the type should be "ConvolutionReluPoolingLayer2", but it shows "NN" instead. Do you know how to correct it?

**Comment by mdenna-synaptics** [comment]
Hi,
good questions.

1) sum(by_layer) != total
   by_layer inference times are measured by executing the layers of the network one at a time.
   This involves some overhead to start and stop execution each time, so the sum exceeds the total inference time.
   This is expected and despite this mismatch by_layer timings provide a useful indication of where most of the time is spent

2) extra layers with 0 us inference time

   There are generally 3 layers added at the end of the network.
   These are not present in the original tflite model, but needed to take care of the HW.
   They normally consume just a few μs or 0.

3) Bad layer type in the report

   This is due to a change in our driver. I will fix the report


On Jul 14, 2022, at 16:08, touristourist ***@***.******@***.***>> wrote:

CAUTION: Email originated externally, do not click links or open attachments unless you recognize the sender and know the content is safe.



Hi, about the JSON file, I have some questions.
First, does the 'by_layer' field show the inference time per layer? But when I add all the layers' time, the result exceeds the model's 'inference_us' by a large margin. What's more, there are some layers show 0 μs in the file, I check out my tflite and make sure these layers don't exist in my model.
Second, how to display the correct type of layer? For instance, I created a Conv2D layer, usually, the type should be "ConvolutionReluPoolingLayer2", but it shows "NN" instead. Do you know how to correct it?
